import type { Metadata } from "next";
import { SITE_NAME, SITE_URL } from "@/constants";

/**
 * Single source of truth for a page's `openGraph` + `twitter` metadata.
 *
 * WHY THIS EXISTS: Next's metadata merge is **shallow** — when a page exports its
 * own `openGraph` object it REPLACES the root layout's `openGraph` wholesale, it
 * does NOT merge field-by-field (verified in
 * node_modules/next/dist/docs/.../generate-metadata.md §Merging, and in
 * next/dist/lib/metadata/resolve-metadata.js). Every page here sets its own OG
 * title/description/url, so each was silently dropping the layout's `images`,
 * `siteName` and `locale` → imageless, unbranded social/Viber previews on ~16
 * pages. Routing every page through this builder guarantees those inherited
 * fields are always re-declared, and a future page can't reintroduce the bug.
 *
 * Also emits the Twitter Card (which the site had nowhere): Next does NOT derive
 * `twitter:*` from `openGraph`, so X/Slack cards need their own tags.
 *
 * Spread the result into a page's `Metadata`:
 *   export const metadata = { title, description, alternates: { canonical },
 *     ...buildSocialMeta({ title, description, path: "/carfax" }) };
 */

/**
 * The default share image (site-root-relative — resolved against `metadataBase`).
 * Dimensions/alt are declared centrally so scrapers get exact box sizing.
 * `public/og-cover.png` is the 1200×630 branded card (OG/Twitter recommended
 * size), generated by `scripts/make-og-image.mjs`. NOTE: `OG_IMAGE_WIDTH/HEIGHT`
 * MUST match the actual pixels of the file — bump them if the generator changes.
 */
const DEFAULT_OG_IMAGE = "/og-cover.png";
const OG_IMAGE_WIDTH = 1200;
const OG_IMAGE_HEIGHT = 630;

export type SocialMetaInput = {
  /** Page title used for og:title / twitter:title (may differ from the <title>). */
  title: string;
  /** Page description used for og:description / twitter:description. */
  description: string;
  /** Site-root-relative path, e.g. "/carfax". Omit / "" for the homepage. */
  path?: string;
  /** Per-page share image (root-relative or absolute). Falls back to the site image. */
  image?: string;
  /** OG type — "website" (default) or "article" (blog posts). */
  type?: "website" | "article";
  /** Article-only fields; ignored unless `type: "article"`. */
  article?: {
    publishedTime?: string;
    modifiedTime?: string;
    authors?: string[];
    tags?: string[];
  };
};

/**
 * Build a `{ openGraph, twitter }` fragment with the inherited image/siteName/
 * locale always present. Returns a partial `Metadata` to spread into a page.
 */
export function buildSocialMeta(input: SocialMetaInput): Pick<Metadata, "openGraph" | "twitter"> {
  const { title, description, path = "", image, type = "website", article } = input;
  const url = `${SITE_URL}${path}`;
  const imageUrl = image ?? DEFAULT_OG_IMAGE;

  // Only declare width/height/alt for the known default image; a custom per-page
  // image (car photo, post hero) has unknown pixels, so pass just its URL + alt.
  const images =
    imageUrl === DEFAULT_OG_IMAGE
      ? [{ url: imageUrl, width: OG_IMAGE_WIDTH, height: OG_IMAGE_HEIGHT, alt: title }]
      : [{ url: imageUrl, alt: title }];

  const openGraph: NonNullable<Metadata["openGraph"]> =
    type === "article"
      ? {
          type: "article",
          siteName: SITE_NAME,
          locale: "bg_BG",
          url,
          title,
          description,
          images,
          ...(article?.publishedTime ? { publishedTime: article.publishedTime } : {}),
          ...(article?.modifiedTime ? { modifiedTime: article.modifiedTime } : {}),
          ...(article?.authors ? { authors: article.authors } : {}),
          ...(article?.tags ? { tags: article.tags } : {}),
        }
      : {
          type: "website",
          siteName: SITE_NAME,
          locale: "bg_BG",
          url,
          title,
          description,
          images,
        };

  return {
    openGraph,
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [imageUrl],
    },
  };
}
